In [1]:
import numpy as np
import pandas as pd

In [2]:
ipl24 = pd.read_csv('cricket_data.csv')
ipl24

,2024,Ruturaj Gaikwad,2,0,61,46,30.5,51,119.61,0.1,...,2.1,0.5,0.6,0.7,0.8,0.9,0.10,0.11,0.12,0.13
0,2023,Ruturaj Gaikwad,16,1,590,92,42.14,400,147.50,0,...,16,0,0,0,0,0.00,0.00,0.0,0,0
1,2022,Ruturaj Gaikwad,14,0,368,99,26.29,291,126.46,0,...,14,0,0,0,0,0.00,0.00,0.0,0,0
2,2021,Ruturaj Gaikwad,16,2,635,101*,45.35,466,136.26,1,...,16,0,0,0,0,0.00,0.00,0.0,0,0
3,2020,Ruturaj Gaikwad,6,2,204,72,51.00,169,120.71,0,...,6,0,0,0,0,0.00,0.00,0.0,0,0
4,2023,Devon Conway,16,2,672,92*,51.69,481,139.71,0,...,16,0,0,0,0,0.00,0.00,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,2023,Mayank Markande,10,3,21,18*,0.00,13,161.54,0,...,10,228,300,12,Apr-15,25.00,7.89,19.0,1,0
1125,2022,Mayank Markande,2,0,0,0,0.00,0,0.00,0,...,2,42,57,1,Jan-26,57.00,8.14,42.0,0,0
1126,2021,Mayank Markande,1,0,0,0,0.00,0,0.00,0,...,1,18,26,0,0/26,0.00,8.66,0.0,0,0
1127,2019,Mayank Markande,3,1,6,6,6.00,5,120.00,0,...,3,36,59,1,Jan-23,59.00,9.83,36.0,0,0
1128,2018,Mayank Markande,14,4,21,7*,10.50,24,87.50,0,...,14,264,368,15,Apr-23,24.53,8.36,17.6,1,0

In [5]:
new_header = ['Year' , 'Player_Name' , 'Matches_Batted' , 'Not_Outs' , 'Runs_Scored' , 'Highest_Score' , 'Batting_Average' , 'Balls_Faced' , 'Batting_Strike_Rate','Centuries','Half_Centuries','Fours' ,'Sixes','Catches_Taken','Stumpings','Matches_Bowled','Balls_Bowled','Runs_Conceded' ,'Wickets_Taken','Best_Bowling_Match','Bowling_Average','Economy_Rate','Bowling_Strike_Rate','Four_Wicket_Hauls','Five_Wicket_Hauls']

In [13]:
ipl24 = pd.read_csv('cricket_data.csv', names= new_header)
ipl24

,Year,Player_Name,Matches_Batted,Not_Outs,Runs_Scored,Highest_Score,Batting_Average,Balls_Faced,Batting_Strike_Rate,Centuries,...,Matches_Bowled,Balls_Bowled,Runs_Conceded,Wickets_Taken,Best_Bowling_Match,Bowling_Average,Economy_Rate,Bowling_Strike_Rate,Four_Wicket_Hauls,Five_Wicket_Hauls
0,2024,Ruturaj Gaikwad,2,0,61,46,30.50,51,119.61,0,...,2,0,0,0,0,0.00,0.00,0.0,0,0
1,2023,Ruturaj Gaikwad,16,1,590,92,42.14,400,147.50,0,...,16,0,0,0,0,0.00,0.00,0.0,0,0
2,2022,Ruturaj Gaikwad,14,0,368,99,26.29,291,126.46,0,...,14,0,0,0,0,0.00,0.00,0.0,0,0
3,2021,Ruturaj Gaikwad,16,2,635,101*,45.35,466,136.26,1,...,16,0,0,0,0,0.00,0.00,0.0,0,0
4,2020,Ruturaj Gaikwad,6,2,204,72,51.00,169,120.71,0,...,6,0,0,0,0,0.00,0.00,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1125,2023,Mayank Markande,10,3,21,18*,0.00,13,161.54,0,...,10,228,300,12,Apr-15,25.00,7.89,19.0,1,0
1126,2022,Mayank Markande,2,0,0,0,0.00,0,0.00,0,...,2,42,57,1,Jan-26,57.00,8.14,42.0,0,0
1127,2021,Mayank Markande,1,0,0,0,0.00,0,0.00,0,...,1,18,26,0,0/26,0.00,8.66,0.0,0,0
1128,2019,Mayank Markande,3,1,6,6,6.00,5,120.00,0,...,3,36,59,1,Jan-23,59.00,9.83,36.0,0,0
1129,2018,Mayank Markande,14,4,21,7*,10.50,24,87.50,0,...,14,264,368,15,Apr-23,24.53,8.36,17.6,1,0

In [15]:
ipl24.shape

(1130, 25)

In [16]:
ipl24.isnull().sum()

Year                   0
Player_Name            0
Matches_Batted         0
Not_Outs               0
Runs_Scored            0
Highest_Score          0
Batting_Average        0
Balls_Faced            0
Batting_Strike_Rate    0
Centuries              0
Half_Centuries         0
Fours                  0
Sixes                  0
Catches_Taken          0
Stumpings              0
Matches_Bowled         0
Balls_Bowled           0
Runs_Conceded          0
Wickets_Taken          0
Best_Bowling_Match     0
Bowling_Average        0
Economy_Rate           0
Bowling_Strike_Rate    0
Four_Wicket_Hauls      0
Five_Wicket_Hauls      0
dtype: int64

In [18]:
ipl24.to_csv('output.csv', index=False)